module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    USER: 'USER'
  },
  LEAD_STATUS: {
    NEW: 'NEW',
    CONTACTED: 'CONTACTED',
    FOLLOW_UP: 'FOLLOW_UP',
    CLOSED: 'CLOSED'
  },
  COMMUNICATION_TYPES: {
    CALL: 'CALL',
    WHATSAPP: 'WHATSAPP',
    EMAIL: 'EMAIL',
    MEETING: 'MEETING',
    SITE_VISIT: 'SITE_VISIT'
  },
  FOLLOW_UP_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    MISSED: 'MISSED'
  },
  FOLLOW_UP_PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH'
  },
  ACTIVITY_TYPES: {
    LEAD_CREATED: 'LEAD_CREATED',
    LEAD_UPDATED: 'LEAD_UPDATED',
    LEAD_ASSIGNED: 'LEAD_ASSIGNED',
    LEAD_REASSIGNED: 'LEAD_REASSIGNED',
    COMMUNICATION_ADDED: 'COMMUNICATION_ADDED',
    FOLLOWUP_ADDED: 'FOLLOWUP_ADDED',
    FOLLOWUP_UPDATED: 'FOLLOWUP_UPDATED',
    STATUS_CHANGED: 'STATUS_CHANGED',
    LEAD_CLOSED: 'LEAD_CLOSED'
  }
};
